backend:
  name: git-gateway
  branch: master
media_folder: public/image
public_folder: /image
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'content/home.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - label: 'Cats'
            name: 'cats'
            widget: list
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'text' }
  - name: 'module'
    label: 'Modul'
    files:
      - label: 'Slider'
        name: 'slider'
        file: 'content/slider.md'
        fields:
          - { label: 'Başlık', name: 'baslik', widget: 'string' }
          - label: 'Slide'
            name: 'slider'
            widget: list
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Açıklama', name: 'description', widget: 'text' }
              - { label: 'Url', name: 'url', widget: 'string' }
              - label: 'Image'
                name: 'image'
                widget: 'image'
                default: '/image/slider/bg_1.jpg'
                media_library:
                  config:
                    multiple: false
      - label: 'Etkinlikler'
        name: 'etkinlik'
        file: 'content/etkinlik.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Açıklama', name: 'description', widget: 'text' }
          - label: 'Image'
            name: 'image'
            widget: 'image'
            default: '/image/about.jpg'
          - label: 'Etkinlikler'
            name: 'etkinlikler'
            widget: list
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'text' }
              - { label: 'Icon', name: 'icon', allow_add: false, media_folder: '/svg', widget: 'image'}
